### ISSUE TITLE
"Categories" support

### ISSUE THREAD

**Issue by teckloide** [ellipticaljs/paper-autocomplete#15]
Hi! have you planned to add a "group by category" feature ? i mean something like the facebook search textbox , where you can search the same text on multiple categories (persons , groups , etc) and display it on the same way. Thanks!

**Comment by tachyon1337** [comment]
@teckloide 

Actually, I have an autocomplete component that looks/works similar to Facebook's version. I just haven't published it.  When I do publish it, it will be in a separate repository because it works differently than paper-autocomplete. The primary difference is that in the Facebook style version, you have to template the element's instance light DOM for your content. This allows for arbitrary groupings you mentioned above with custom visual elements like icons, avatars, small thumbs, svgs, etc.

**Comment by teckloide** [comment]
Sounds great @tachyon1337 ! my question is because i need a simultaneous text based search on two catalogs at the same time , so i was available to make a fork because the idea of add the feature to this component could break the backward compatibility along with some tricky operations that can slow down the performance. I'll be waiting for this new component , and you can count on me to debug it.
