### ISSUE TITLE
key events not working with native shadow dom?

### ISSUE THREAD

**Issue by StokeMasterJack** [ellipticaljs/paper-autocomplete#18]
I created a small sample page that uses paper-autocomplete with my ajax api and it works perfectly.

But as soon as I added this line:

`<script>window.Polymer = {dom: 'shadow' };</script>`

the down arrow key stopped working.

**Comment by StokeMasterJack** [comment]
I wrote blog post describing the more general problem here:

https://medium.com/@daveford/shady-dom-problems-b7978508a9af#.cdgwo66ix

**Comment by tachyon1337** [comment]
@StokeMasterJack 

Yeah, the keyboard support that I rolled relies on a simple querySelector on paper-item descendant children. Works well enough for shady dom...but that's not going to work with shadow dom. Since shadow dom is only supported on chrome, pollyfilling the spec is not recommended for production and the spec itself may or may not be stable/final, I I'm going to stick to supporting only shady dom for the time being. That being said, I certainly will consider merging pull requests that fix the shadow dom issue.

**Comment by StokeMasterJack** [comment]
I am developing a "chrome only" app with shadow DOM turned on. Switching to Shady DOM at this point would break a million things. So I modified the getItems function as shown below:

```
_getItems:function(){
  //this.querySelectorAll('paper-item') does not work when
  //native shadow dom but this does:
  return this.shadowRoot.querySelectorAll('paper-item');
},
```

I'm not sure how to make this work with both shady and shadow. But it works for shadow. Thanks.

**Comment by tachyon1337** [comment]
@StokeMasterJack 

You could implement a `useShadowDom` attribute/property. If set to true in the component attribute, then use the `this.shadowRoot.querySelectorAll` in the `_getItems` method. I will look to implement that as well in the next version.

`return (this.useShadowDom) ? this.shadowRoot.querySelectorAll('paper-item') : this.querySelectorAll('paper-item')`

Thanx

**Comment by StokeMasterJack** [comment]
Or better yet, you can try this. It works. I tested it both with and without Shadow DOM:

```
var wantsShadow = window.Polymer.Settings.dom === 'shadow';
var hasShadow = Boolean(Element.prototype.createShadowRoot);
var useShadow = wantsShadow && hasShadow;

if(useShadow){
  return this.shadowRoot.querySelectorAll('paper-item');
}else{
  //must be using shady
  return this.querySelectorAll('paper-item')
}
```
